### ISSUE TITLE
Re-use the aplication & save problem

### ISSUE THREAD

**Issue by sKeneth** [WEGFan/Geometry-Dash-Savefile-Fix#3] opened 2021-01-17 05:34 UTC
Hello, your aplication let me enter in the game without deleting the CCLocalLevels (my corrupted files), but when closing GD the problem keep persisting and I have to re-use the app, is that the functionality or it's another problem that I have?

Also, i tried many times saving the information to the cloud in-game but doesn't let me, is it related to de corrupted files?

**Comment by WEGFan** [comment] 2021-01-17 07:24
This is the game's bug, Robtop said it will be fixed in 2.2, so currently there are no other ways to solve this.

Failed saving to the cloud may caused by various problems, for example, the game won't let you save if your save file is too large (around 12 MB in total), you can ask for help in **#support** channel in [discord server](https://discord.gg/geometrydash)

**Closed as completed** 2021-01-17 07:25 UTC
